package com.bty.karaoke.mememusicboxservice.constant;

public enum LogType {
    OPEN_ROOM,
    UPDATE_MEMBER_OF_INVOICE,
    DELETE_MEMBER_OF_INVOICE,
    CREATE_PRODUCT_OF_INVOICE,
    UPDATE_PRODUCT_OF_INVOICE,
    TRANSFER_ROOM_OF_INVOICE,
    CHECK_OUT_INVOICE,
    PAYMENT_CONFIRMATION,
    CHECK_IN_ROOMBOOKING,
    CANCEL_ROOMBOOKING,
}
